const WORDSCOOP_API='https://wordscoop-api.darkgeneration77.workers.dev';
const WORDSCOOP_KEY='wordscoop_v3';

const WordScoopCloud=(()=>{
  let syncing=false;
  function load(){try{return JSON.parse(localStorage.getItem(WORDSCOOP_KEY)||'null')}catch(e){return null}}
  function save(d){localStorage.setItem(WORDSCOOP_KEY,JSON.stringify(d))}
  function makeId(d){let id;do{id='WS-'+String(Math.floor(100000+Math.random()*900000))}while(Object.values(d?.profiles||{}).some(p=>p?.meta?.id===id));return id}
  function ensure(d){if(!d)return null;d.profiles=d.profiles||{};d.active=d.active||Object.keys(d.profiles)[0]||'Student';d.profiles[d.active]=d.profiles[d.active]||{themes:{},wrong:{},mastery:{},attempts:[]};let p=d.profiles[d.active];p.meta=p.meta||{};p.meta.id=p.meta.id||makeId(d);p.meta.createdAt=p.meta.createdAt||new Date().toISOString();return p}
  function cleanProfile(p){let x=JSON.parse(JSON.stringify(p||{}));x.meta=x.meta||{};delete x.meta.cloudFingerprint;delete x.meta.cloudUpdatedAt;delete x.meta.lastSync;return x}
  function fingerprint(p){let s=JSON.stringify(cleanProfile(p)),h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return (h>>>0).toString(16)}
  async function api(path,opts={}){let r=await fetch(WORDSCOOP_API+path,{...opts,headers:{'Content-Type':'application/json',...(opts.headers||{})}});let j={};try{j=await r.json()}catch(e){}return {ok:r.ok,status:r.status,data:j}}
  async function upload(d,p){let id=p.meta.id,name=d.active,r=await api('/student/'+encodeURIComponent(id),{method:'POST',body:JSON.stringify({student_name:name,profile:cleanProfile(p)})});if(!r.ok)throw new Error(r.data?.error||'Cloud save failed');p.meta.cloudUpdatedAt=r.data.updated_at||new Date().toISOString();p.meta.cloudFingerprint=fingerprint(p);p.meta.lastSync=new Date().toISOString();save(d);return r.data}
  async function syncActive(){if(syncing)return;let d=load();if(!d)return;let p=ensure(d);save(d);if(!p?.meta?.id)return;syncing=true;status('Syncing…');try{let r=await api('/student/'+encodeURIComponent(p.meta.id));if(r.status===404){await upload(d,p);status('Cloud saved');return}if(!r.ok)throw new Error(r.data?.error||'Cloud read failed');let current=fingerprint(p),last=p.meta.cloudFingerprint;if(last&&current===last){let remoteTime=Date.parse(r.data.updated_at||0),localCloudTime=Date.parse(p.meta.cloudUpdatedAt||0);if(r.data.profile&&remoteTime>localCloudTime){let remote=r.data.profile;remote.meta=remote.meta||{};remote.meta.id=p.meta.id;remote.meta.createdAt=remote.meta.createdAt||p.meta.createdAt;remote.meta.cloudUpdatedAt=r.data.updated_at;remote.meta.cloudFingerprint=fingerprint(remote);remote.meta.lastSync=new Date().toISOString();d.profiles[d.active]=remote;save(d);status('Cloud updated');setTimeout(()=>location.reload(),250);return}}else if(!last){let hasLocal=Object.keys(p.themes||{}).length||(p.attempts||[]).length||Object.keys(p.wrong||{}).length||(p.home?.owned||[]).length||Number(p.home?.spent)||0;if(!hasLocal&&r.data.profile){let remote=r.data.profile;remote.meta=remote.meta||{};remote.meta.id=p.meta.id;remote.meta.cloudUpdatedAt=r.data.updated_at;remote.meta.cloudFingerprint=fingerprint(remote);remote.meta.lastSync=new Date().toISOString();d.profiles[d.active]=remote;save(d);status('Cloud loaded');setTimeout(()=>location.reload(),250);return}}await upload(d,p);status('Cloud saved')}catch(e){console.warn('Word Scoop cloud sync:',e);status('Offline · saved locally')}finally{syncing=false}}
  async function loginById(id){id=String(id||'').trim().toUpperCase();if(!/^WS-\d{6}$/.test(id))throw new Error('Student ID must look like WS-123456');let r=await api('/student/'+encodeURIComponent(id));if(!r.ok)throw new Error(r.data?.error||'Student not found');let d=load()||{active:'Student',profiles:{}},name=r.data.student_name||id,remote=r.data.profile||{themes:{},wrong:{},mastery:{},attempts:[]};remote.meta=remote.meta||{};remote.meta.id=id;remote.meta.cloudUpdatedAt=r.data.updated_at;remote.meta.cloudFingerprint=fingerprint(remote);remote.meta.lastSync=new Date().toISOString();d.profiles=d.profiles||{};d.profiles[name]=remote;d.active=name;save(d);return name}
  function status(text){let e=document.getElementById('cloudSyncStatus');if(!e){e=document.createElement('div');e.id='cloudSyncStatus';e.style.cssText='position:fixed;right:12px;bottom:12px;z-index:9999;background:#542f1f;color:#fff7df;border-radius:999px;padding:8px 12px;font:700 12px system-ui;box-shadow:0 3px 12px #0002';document.body.appendChild(e)}e.textContent=text}
  function injectLogin(){let row=document.querySelector('.student-home .row');if(!row||document.getElementById('cloudLoginBtn'))return;let b=document.createElement('button');b.className='btn';b.id='cloudLoginBtn';b.textContent='Cloud Student ID';b.onclick=async()=>{let id=prompt('Enter Student ID (example: WS-123456)');if(!id)return;try{status('Loading cloud…');await loginById(id);location.reload()}catch(e){alert(e.message);status('Cloud login failed')}};row.insertBefore(b,row.firstChild)}
  function loadTestLock(){if(!/^\/.*theme-\d+\.html$/.test(location.pathname)||document.querySelector('script[data-test-lock]'))return;let s=document.createElement('script');s.src='test-lock.js?v=20260831d';s.dataset.testLock='1';document.body.appendChild(s)}
  function boot(){injectLogin();syncActive();setTimeout(loadTestLock,0)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else setTimeout(boot,0);
  window.addEventListener('online',()=>syncActive());
  return {syncActive,loginById,status};
})();
window.WordScoopCloud=WordScoopCloud;