const STORE_KEY='wordscoop_v3';
let soundOn=true, ac=null, streak=0, britishVoice=null, currentMode='practice', questionOrder=[];

function blankProfile(){return {themes:{},wrong:{},mastery:{},attempts:[]}}
function loadStore(){let d;try{d=JSON.parse(localStorage.getItem(STORE_KEY)||'null')}catch(e){}if(!d){d={active:'Student',profiles:{Student:blankProfile()}};try{const old=JSON.parse(localStorage.getItem('wordscoop_v2')||'null');if(old)d.profiles.Student={themes:old.themes||{},wrong:old.wrong||{},mastery:{},attempts:[]}}catch(e){}saveStore(d)}d.profiles=d.profiles||{};d.active=d.active||Object.keys(d.profiles)[0]||'Student';d.profiles[d.active]=d.profiles[d.active]||blankProfile();return d}
function saveStore(d){localStorage.setItem(STORE_KEY,JSON.stringify(d))}
function cloudSave(){if(window.WordScoopCloud?.syncActive)setTimeout(()=>window.WordScoopCloud.syncActive(),40)}
function activeProfile(){let d=loadStore();return d.profiles[d.active]}
function activeName(){return loadStore().active}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function norm(s){return(s||'').trim().toLowerCase().replace(/\s+/g,' ')}
function pattern(w){return [...w].map((c,i)=>/[a-z]/i.test(c)?(i===0?c:'_'):c).join(' ')}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function audio(){if(!ac){const A=window.AudioContext||window.webkitAudioContext;if(A)ac=new A()}if(ac&&ac.state==='suspended')ac.resume();return ac}
function tone(f,d=.12,delay=0,gain=.13){if(!soundOn)return;let c=audio();if(!c)return;let o=c.createOscillator(),g=c.createGain();o.type='triangle';o.frequency.value=f;g.gain.value=gain;o.connect(g);g.connect(c.destination);o.start(c.currentTime+delay);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+delay+d);o.stop(c.currentTime+delay+d+.02)}
function goodS(){tone(523,.12,0,.13);tone(659,.13,.08,.13);tone(784,.16,.16,.13)}function badS(){tone(220,.12,0,.11);tone(196,.16,.1,.11)}function winS(){[523,659,784,1046].forEach((f,i)=>tone(f,.18,i*.08,.13))}function completeS(){tone(392,.1,0,.08);tone(523,.12,.08,.09)}
function toast(msg,err=false){let e=document.querySelector('.toast');if(!e)return;e.textContent=msg;e.className='toast'+(err?' err':'');void e.offsetWidth;e.classList.add('show')}
function fx(el,ok){if(ok){streak++;el&&el.classList.add('pop');toast(['Excellent!','Perfect spelling!','Great job!','You got it!','Brilliant!','Strong work!'][Math.random()*6|0]);goodS();if(streak>=4)confetti()}else{streak=0;el&&el.classList.add('shake');toast(['Almost there!','Try again!','Check the spelling!','Keep going!','You can fix it!'][Math.random()*5|0],true);badS()}setTimeout(()=>el&&el.classList.remove('pop','shake'),500)}
function confetti(){let cols=['#ffc928','#f59b23','#f3c4c7','#cfe8cf','#7a4a2e'];for(let i=0;i<18;i++){let p=document.createElement('i');p.className='piece';p.style.left=(45+Math.random()*10)+'vw';p.style.top='22vh';p.style.background=cols[i%cols.length];p.style.setProperty('--x',(Math.random()*260-130)+'px');p.style.setProperty('--y',(120+Math.random()*230)+'px');p.style.setProperty('--r',(Math.random()*720-360)+'deg');document.body.appendChild(p);setTimeout(()=>p.remove(),950)}}
function chooseBritishVoice(){if(!('speechSynthesis' in window))return null;const vs=speechSynthesis.getVoices(),preferred=['Google UK English Female','Microsoft Sonia Online (Natural) - English (United Kingdom)','Microsoft Ryan Online (Natural) - English (United Kingdom)','Daniel','Serena','Kate','Stephanie'];britishVoice=preferred.map(n=>vs.find(v=>v.name===n)).find(Boolean)||vs.find(v=>/^en-GB$/i.test(v.lang))||vs.find(v=>/^en[-_]GB/i.test(v.lang))||null;return britishVoice}
if('speechSynthesis' in window){chooseBritishVoice();speechSynthesis.onvoiceschanged=chooseBritishVoice}
function speak(w,rate=.72){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(w);u.lang='en-GB';u.rate=rate;u.pitch=1;u.volume=1;u.voice=chooseBritishVoice();speechSynthesis.speak(u)}
function masteryLabel(n){return n>=4?'Mastered':n===3?'Almost Mastered':n>=1?'Learning':'New'}
function updateMastery(theme,word,ok){let d=loadStore(),p=d.profiles[d.active],k=theme+'|'+word,m=p.mastery[k]||{score:0,correct:0,wrong:0};if(ok){m.correct++;m.score=Math.min(4,(m.score||0)+1)}else{m.wrong++;m.score=Math.max(0,(m.score||0)-1)}p.mastery[k]=m;saveStore(d)}
function recordWrong(theme,word,typed,ok){let d=loadStore(),p=d.profiles[d.active],k=theme+'|'+word;if(ok){if(p.wrong[k]){p.wrong[k].streak=(p.wrong[k].streak||0)+1;if(p.wrong[k].streak>=2)delete p.wrong[k]}}else p.wrong[k]={theme,word,typed:typed||'',streak:0};saveStore(d)}
function saveAttempt(theme,score,mode){let d=loadStore(),p=d.profiles[d.active];p.themes[theme]=p.themes[theme]||{};p.themes[theme].best=Math.max(p.themes[theme].best||0,score);p.themes[theme].last=score;p.themes[theme].date=new Date().toISOString();p.attempts=p.attempts||[];p.attempts.unshift({theme,score,mode,date:new Date().toISOString()});p.attempts=p.attempts.slice(0,200);saveStore(d);cloudSave()}
function renderProfileStrip(){const main=document.querySelector('main'),nav=main.querySelector('.nav');let box=document.createElement('div');box.className='profile-strip';box.innerHTML=`<b>Student:</b> <span id="activeStudent">${esc(activeName())}</span><button class="modebtn" id="switchStudent">Switch Student</button><a class="modebtn teacher-link" href="home.html">My Home</a><a class="modebtn teacher-link" href="teacher.html">Teacher Dashboard</a>`;nav.insertAdjacentElement('afterend',box);box.querySelector('#switchStudent').onclick=()=>{let d=loadStore(),name=prompt('Student name:',d.active);if(!name)return;name=name.trim();if(!name)return;d.profiles[name]=d.profiles[name]||blankProfile();d.active=name;saveStore(d);location.reload()}}
function refreshStatus(id){let d=loadStore(),p=d.profiles[d.active],x=p.themes[id]||{},best=x.best,st=best===8?3:best>=6?2:best>=4?1:0;bestBadge.textContent='Best: '+(best===undefined?'—':best)+' / 8';starBadge.textContent='★'.repeat(st)+'☆'.repeat(3-st);let arr=Object.values(p.wrong||{}).filter(x=>x.theme===id);wrongList.innerHTML=arr.length?arr.map(x=>`<button class="wrongchip" data-word="${esc(x.word)}">${esc(x.word)} · ${x.streak||0}/2 correct</button>`).join(''):'<span>No wrong words yet.</span>';wrongList.querySelectorAll('.wrongchip').forEach(b=>b.onclick=()=>startWrongReview(b.dataset.word));document.querySelectorAll('[data-mastery]').forEach(e=>{let m=p.mastery[id+'|'+e.dataset.mastery]||{score:0};e.textContent=masteryLabel(m.score)})}
function renderQuestions(){let list=questionOrder.map(i=>window.THEME.words[i]);qs.innerHTML=list.map((w,i)=>`<div class="q" data-a="${esc(w.word)}"><b>${i+1}.</b> <span class="qdef">${esc(w.definition)}</span><button class="listen-btn" data-word="${esc(w.word)}" title="Listen">Listen</button><div class="pattern">${pattern(w.word)}</div><input class="answer" autocomplete="off" spellcheck="false"></div>`).join('');qs.querySelectorAll('.listen-btn').forEach(b=>b.onclick=()=>speak(b.dataset.word))}
function setMode(mode){currentMode=mode;themeBox.classList.toggle('test-mode',mode==='test');themeBox.classList.toggle('listen-mode',mode==='listen');document.querySelectorAll('.modebtn[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));if(mode==='listen')document.querySelectorAll('.qdef').forEach(e=>e.textContent='Listen and type the word.');else questionOrder.forEach((idx,j)=>{let e=document.querySelectorAll('.qdef')[j];if(e)e.textContent=window.THEME.words[idx].definition})}
function render(){const id=window.THEME_ID||1,t=window.THEME,main=document.querySelector('main');document.title=`Theme ${id} — Word Scoop`;document.querySelector('#themeTitle').textContent=t.title;renderProfileStrip();questionOrder=shuffle([...Array(t.words.length).keys()]);let rows=t.words.map((w,i)=>`<tr><td>${i+1}</td><td><b>${esc(w.word)}</b><button class="speak" data-word="${esc(w.word)}">Speak</button></td><td>${esc(w.zh)}</td><td>${esc(w.definition)}</td><td>${esc(w.clue)}</td><td><span class="mastery" data-mastery="${esc(w.word)}">New</span></td></tr>`).join('');main.innerHTML+=`<section class="theme" id="themeBox"><h2>Theme ${id}</h2><p><b>${esc(t.title)}</b></p><div class="theme-status"><span class="resultbadge" id="bestBadge">Best: — / 8</span><span class="resultbadge" id="starBadge">☆☆☆</span><span>Progress saves automatically</span></div><div class="modebar"><b>Mode:</b><button class="modebtn active" data-mode="practice">Practice</button><button class="modebtn" data-mode="test">Test</button><button class="modebtn" data-mode="listen">Listen & Type</button><button class="modebtn" id="reshuffle">Shuffle Questions</button></div><details><summary>Open Notes</summary><div class="tablewrap"><table><thead><tr><th>#</th><th>Word</th><th>华语</th><th>Definition</th><th>Key Clue</th><th>Mastery</th></tr></thead><tbody>${rows}</tbody></table></div></details><section class="practice"><h3>Spelling Practice — 8 Questions</h3><div id="qs"></div><div class="row"><button class="btn" id="check">Check Answers</button><button class="btn" id="reset">Reset</button></div><div class="score" id="score">Score: 0 / 8</div></section><section class="wrongbox"><h3>Wrong Words Revision</h3><p>Each wrong word must be answered correctly twice before it disappears.</p><div class="wronglist" id="wrongList"></div><div id="wrongReview"></div></section><section class="game"><h3 id="gtitle"></h3><div id="garea"></div></section></section>`;renderQuestions();document.querySelectorAll('.speak').forEach(b=>b.onclick=()=>speak(b.dataset.word));document.querySelectorAll('.modebtn[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));reshuffle.onclick=()=>{questionOrder=shuffle(questionOrder);renderQuestions();setMode(currentMode)};check.onclick=checkAnswers;reset.onclick=()=>{document.querySelectorAll('.answer').forEach(x=>{x.value='';x.classList.remove('good','bad')});score.textContent='Score: 0 / 8'};refreshStatus(id);startGame(t)}
function checkAnswers(){const id=window.THEME_ID||1;let g=0;document.querySelectorAll('.q').forEach(q=>{let i=q.querySelector('input'),ok=norm(i.value)===norm(q.dataset.a);i.classList.toggle('good',ok);i.classList.toggle('bad',!ok);if(ok)g++;updateMastery(id,q.dataset.a,ok);recordWrong(id,q.dataset.a,i.value,ok)});saveAttempt(id,g,currentMode);score.textContent=`Score: ${g} / 8`;refreshStatus(id);if(g===8){toast('Perfect! 8 / 8');winS();confetti()}else{streak=0;toast(`Completed: ${g} / 8. Review the highlighted words.`);completeS()}window.dispatchEvent(new CustomEvent('wordscoop-test-submitted',{detail:{theme:id,score:g,mode:currentMode}}))}
function startWrongReview(word){const id=window.THEME_ID||1,w=window.THEME.words.find(x=>x.word===word);if(!w)return;wrongReview.innerHTML=`<div class="review-card"><b>${esc(w.definition)}</b><button class="listen-btn" id="reviewListen">Listen</button><div class="row"><input id="reviewInput" autocomplete="off"><button class="btn" id="reviewCheck">Check</button></div><div id="reviewStatus"></div></div>`;reviewListen.onclick=()=>speak(word);reviewCheck.onclick=()=>{let ok=norm(reviewInput.value)===norm(word);updateMastery(id,word,ok);recordWrong(id,word,reviewInput.value,ok);reviewStatus.textContent=ok?'Correct. One step closer to mastered.':'Try again.';ok?goodS():badS();refreshStatus(id);cloudSave()}}
function startGame(t){const names=['','Flip Match','Definition Hunter','Letter Scramble','Missing Letters','Falling Words','Spelling Battle'];gtitle.textContent=names[t.game];if(t.game===1)flip(t);if(t.game===2)hunter(t);if(t.game===3)inputGame(t,'scramble');if(t.game===4)inputGame(t,'missing');if(t.game===5)hunter(t);if(t.game===6)inputGame(t,'battle')}
function finishGame(area,s){area.innerHTML=`<b>Completed. Score: ${s} / 8</b>`;winS();confetti()}
function flip(t){let a=[];t.words.forEach((w,i)=>a.push({i,k:'w',v:w.word},{i,k:'m',v:w.zh}));a=shuffle(a);garea.innerHTML='<div class="cards">'+a.map(x=>`<button class="card hidden" data-i="${x.i}" data-k="${x.k}" data-v="${esc(x.v)}">?</button>`).join('')+'</div>';let first=null,lock=false,matched=0;garea.querySelectorAll('.card').forEach(b=>b.onclick=()=>{if(lock||b.classList.contains('good')||b===first)return;b.textContent=b.dataset.v;b.classList.remove('hidden');if(!first){first=b;return}if(first.dataset.i===b.dataset.i&&first.dataset.k!==b.dataset.k){first.classList.add('good');b.classList.add('good');matched++;fx(b,true);first=null;if(matched===8)finishGame(garea,8)}else{lock=true;let f=first;first=null;fx(b,false);setTimeout(()=>{[f,b].forEach(x=>{x.textContent='?';x.classList.add('hidden')});lock=false},650)}})}
function hunter(t){let order=shuffle(t.words),i=0,s=0;function next(){if(i>=8)return finishGame(garea,s);let q=order[i],pool=shuffle(t.words.filter(x=>x.word!==q.word).map(x=>x.word)).slice(0,3),opts=shuffle([q.word,...pool]);garea.innerHTML=`<div class="prompt">${esc(q.definition)}</div><div class="choices">${opts.map(x=>`<button class="choice">${esc(x)}</button>`).join('')}</div><div class="score">Score: ${s} / 8</div>`;garea.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{let ok=norm(b.textContent)===norm(q.word);if(ok){s++;fx(b,true)}else fx(b,false);updateMastery(window.THEME_ID,q.word,ok);setTimeout(()=>{i++;next()},500)})}next()}
function scrambleWord(w){return shuffle([...w].filter(c=>/[a-z]/i.test(c))).join(' ')}
function inputGame(t,mode){let order=shuffle(t.words),i=0,s=0;function next(){if(i>=8)return finishGame(garea,s);let q=order[i],hint=mode==='scramble'?scrambleWord(q.word):mode==='missing'?pattern(q.word):q.definition;garea.innerHTML=`<div class="prompt">${esc(hint)}</div><div class="row"><input id="gameInput" autocomplete="off"><button class="btn" id="gameCheck">Check</button></div><div class="score">Score: ${s} / 8</div>`;function go(){let ok=norm(gameInput.value)===norm(q.word);if(ok){s++;fx(gameInput,true)}else fx(gameInput,false);updateMastery(window.THEME_ID,q.word,ok);i++;setTimeout(next,400)}gameCheck.onclick=go;gameInput.onkeydown=e=>{if(e.key==='Enter')go()};gameInput.focus()}next()}
document.addEventListener('DOMContentLoaded',()=>{render();sound.onclick=()=>{soundOn=!soundOn;sound.textContent='Sound: '+(soundOn?'ON':'OFF')}});